### ISSUE TITLE
Option for string tokenization

### ISSUE THREAD

**Issue by commandz0** [adriweb/tivars_lib_cpp#9]
When tokenizing a program, tokens inside of strings are replaced with single-character tokens rather than the longest token available. This is not always desirable, as strings are sometimes stored into equations or lists or evaluated. There should be an option in TH_Tokenized::makeDataFromString to tokenize the contents of strings in the same way as the rest of the program.

**Comment by adriweb** [comment]
Yep, I've had that in the back of my mind for a while, I guess I'll add it soon. Should be easy.

Note that the reason behind the default behavior is when people got 8xp that were displayed correctly in French but not in English (and vice-versa) depending on their calc configuration.... because tokens get translated inside strings too. And of course, in the middle of a carefully written string, seeing random translated words made no sense or broke the intended layout/display etc.

**Comment by adriweb** [comment]
Thanks :)
